### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by dasda-asd** [natesimon/MonoNav#3]
This is a very good job. I run the fuse_dept. py file and the following error occurs.

The follow :
[Open3D Error] (class std::shared_ptr<class open3d::core::DeviceHashBackend> __cdecl open3d::core::CreateDeviceHashBackend(__int64,const class open3d::core::Dtype &,const class open3d::core::SizeVector &,const class std::vector<class open3d::core::Dtype,class std::allocator<class open3d::core::Dtype> > &,const class std::vector<class open3d::core::SizeVector,class std::allocator<class open3d::core::SizeVector> > &,const class open3d::core::Device &,const enum open3d::core::HashBackendType &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\DeviceHashBackend.cpp:38: Unimplemented device

Traceback (most recent call last):
  File "C:\Users\23860\Desktop\深度估计与SLAM融合\参考论文\MonoNav\MonoNav-main\fuse_depth.py", line 51, in <module>
    vbg = VoxelBlockGrid(depth_scale, depth_max, trunc_voxel_multiplier, o3d.core.Device(device))
  File "C:\Users\23860\Desktop\深度估计与SLAM融合\参考论文\MonoNav\MonoNav-main\utils\utils.py", line 50, in __init__
    self.vbg = o3d.t.geometry.VoxelBlockGrid(
RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::core::DeviceHashBackend> __cdecl open3d::core::CreateDeviceHashBackend(__int64,const class open3d::core::Dtype &,const class open3d::core::SizeVector &,const class std::vector<class open3d::core::Dtype,class std::allocator<class open3d::core::Dtype> > &,const class std::vector<class open3d::core::SizeVector,class std::allocator<class open3d::core::SizeVector> > &,const class open3d::core::Device &,const enum open3d::core::HashBackendType &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\DeviceHashBackend.cpp:38: Unimplemented device

I would appreciate it if you could reply to me！

**Comment by natesimon** [comment]
Hi @dasda-asd , this looks like a GPU issue to me. Could you confirm your `device` setting in [config.yml](https://github.com/natesimon/MonoNav/blob/ddb0da5249005492d2580b29f4a6c9066cc22b42/config.yml#L22)?

1. You can try setting `device: "CPU:0"` and retrying `fuse_depth.py`. If the code runs, it is likely the issue is with the GPU.
2. Can you also check whether your GPU is recognized by your computer? (E.g., try running `nvidia-smi` in your terminal.) This is a good way to check whether your GPU is properly recognized.

I hope this helps!

**Comment by natesimon** [comment]
Hi @dasda-asd, was your issue resolved?

**Comment by Realle0815** [comment]
I also encountered the same problem seems to be that Open3d 0.18.0 does not support the ARM architecture needs to download 0.19 but open3d author to give 0.19 download URL can not be opened.
